### ISSUE TITLE
PEP Style changes

### ISSUE THREAD

**Issue by seanwiseman** [Gman0909/eLifeDigestToMP3#6]
There are a few things to address regarding code style and structure. The Pythonic standard is to follow [PEP8](https://pep8.org/).

You can automate these checks with several tools though we have one that makes it even easier to get up and running: [proofeader](https://github.com/elifesciences/proofreader-python)

Usage example:
`pip install proofreader`

Then run the below command in the directory of your project:

`python -m proofreader DigestBot2.py` (the filename can be a list of space sperated files or directories)

**Comment by gmaciocci** [comment]
Thanks. Should be mostly ok now.
